# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'library.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

"""
*------------------------------------------------*
管理员图书管理系统界面的UI设计
UI转py
*------------------------------------------------*
"""
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QAction, QMenu


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1104, 755)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(20, 20, 1051, 621))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox_3 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox.setGeometry(QtCore.QRect(10, 100, 471, 91))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 431, 65))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.p_zengjia = QtWidgets.QPushButton(self.layoutWidget)
        self.p_zengjia.setObjectName("p_zengjia")
        self.gridLayout_2.addWidget(self.p_zengjia, 0, 0, 1, 1)
        self.p_charu = QtWidgets.QPushButton(self.layoutWidget)
        self.p_charu.setObjectName("p_charu")
        self.gridLayout_2.addWidget(self.p_charu, 0, 1, 1, 1)
        self.p_quxiao = QtWidgets.QPushButton(self.layoutWidget)
        self.p_quxiao.setObjectName("p_quxiao")
        self.gridLayout_2.addWidget(self.p_quxiao, 0, 2, 1, 1)
        self.p_sanchu = QtWidgets.QPushButton(self.layoutWidget)
        self.p_sanchu.setObjectName("p_sanchu")
        self.gridLayout_2.addWidget(self.p_sanchu, 1, 0, 1, 1)
        self.p_photo = QtWidgets.QPushButton(self.layoutWidget)
        self.p_photo.setObjectName("p_photo")
        self.gridLayout_2.addWidget(self.p_photo, 1, 1, 1, 1)
        self.p_baocun = QtWidgets.QPushButton(self.layoutWidget)
        self.p_baocun.setObjectName("p_baocun")
        self.gridLayout_2.addWidget(self.p_baocun, 1, 2, 1, 1)
        self.table_view = QtWidgets.QTableView(self.groupBox_3)
        self.table_view.setGeometry(QtCore.QRect(10, 210, 471, 331))
        self.table_view.setObjectName("table_view")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(70, 560, 341, 30))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.JumpPageLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.JumpPageLabel.setObjectName("JumpPageLabel")
        self.horizontalLayout_3.addWidget(self.JumpPageLabel)
        self.lineEdit_tiaozhuan = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_tiaozhuan.setObjectName("lineEdit_tiaozhuan")
        self.horizontalLayout_3.addWidget(self.lineEdit_tiaozhuan)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.PrevButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.PrevButton.setObjectName("PrevButton")
        self.horizontalLayout_3.addWidget(self.PrevButton)
        self.BackButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.BackButton.setObjectName("BackButton")
        self.horizontalLayout_3.addWidget(self.BackButton)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 473, 67))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_chaxun = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_chaxun.setObjectName("lineEdit_chaxun")
        self.horizontalLayout.addWidget(self.lineEdit_chaxun)
        self.comboBox_chaxun = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox_chaxun.setObjectName("comboBox_chaxun")
        self.comboBox_chaxun.addItem("")
        self.comboBox_chaxun.addItem("")
        self.comboBox_chaxun.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_chaxun)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.p_chaxun = QtWidgets.QPushButton(self.layoutWidget2)
        self.p_chaxun.setObjectName("p_chaxun")
        self.verticalLayout_2.addWidget(self.p_chaxun)
        self.p_quxiaoCX = QtWidgets.QPushButton(self.layoutWidget2)
        self.p_quxiaoCX.setObjectName("p_quxiaoCX")
        self.verticalLayout_2.addWidget(self.p_quxiaoCX)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.p_tuichu = QtWidgets.QPushButton(self.layoutWidget2)
        self.p_tuichu.setObjectName("p_tuichu")
        self.horizontalLayout.addWidget(self.p_tuichu)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(30, 70, 82, 431))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget3)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.dbLabPhoto = QtWidgets.QLabel(self.layoutWidget3)
        self.dbLabPhoto.setObjectName("dbLabPhoto")
        self.verticalLayout.addWidget(self.dbLabPhoto)
        spacerItem = QtWidgets.QSpacerItem(20, 388, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(150, 70, 281, 431))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_ISBN = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_ISBN.setObjectName("lineEdit_ISBN")
        self.gridLayout.addWidget(self.lineEdit_ISBN, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_shuming = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_shuming.setObjectName("lineEdit_shuming")
        self.gridLayout.addWidget(self.lineEdit_shuming, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.lineEdit_zuozhe = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_zuozhe.setObjectName("lineEdit_zuozhe")
        self.gridLayout.addWidget(self.lineEdit_zuozhe, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.lineEdit_chubanshe = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_chubanshe.setObjectName("lineEdit_chubanshe")
        self.gridLayout.addWidget(self.lineEdit_chubanshe, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.lineEdit_chubanriqi = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_chubanriqi.setObjectName("lineEdit_chubanriqi")
        self.gridLayout.addWidget(self.lineEdit_chubanriqi, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.lineEdit_pingfen = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_pingfen.setObjectName("lineEdit_pingfen")
        self.gridLayout.addWidget(self.lineEdit_pingfen, 5, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1104, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        # 行为Action

        # 退出行为exit_Act
        self.exit_Act = QAction('Exit', self)
        self.exit_Act.setShortcut('ctrl+Q')
        self.exit_Act.setStatusTip('exit')

        # 在线更新行为
        self.Updata_Act = QAction('更新', self)



        # 菜单栏
        menubar = self.menuBar()
        # 父类菜单栏
        self.filemenu = menubar.addMenu('file')

        # 创建一个子菜单
        self.Updata_Menu = QMenu('Updata', self)
        self.filemenu.addMenu(self.Updata_Menu)



        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图书管理系统"))
        self.table_view.setStatusTip(_translate("MainWindow", "双击修改表格数据，保存需点击保存按钮。"))
        self.groupBox.setTitle(_translate("MainWindow", "图书管理"))
        self.p_zengjia.setText(_translate("MainWindow", "增加记录"))
        self.p_charu.setText(_translate("MainWindow", "插入记录"))
        self.p_quxiao.setText(_translate("MainWindow", "取消"))
        self.p_sanchu.setText(_translate("MainWindow", "删除记录"))
        self.p_photo.setText(_translate("MainWindow", "设置照片"))
        self.p_baocun.setText(_translate("MainWindow", "保存"))
        self.JumpPageLabel.setText(_translate("MainWindow", "跳转到"))
        self.label_9.setText(_translate("MainWindow", "/0页"))
        self.PrevButton.setText(_translate("MainWindow", "前一页"))
        self.BackButton.setText(_translate("MainWindow", "后一页"))
        self.comboBox_chaxun.setItemText(0, _translate("MainWindow", "ISBN"))
        self.comboBox_chaxun.setItemText(1, _translate("MainWindow", "作者"))
        self.comboBox_chaxun.setItemText(2, _translate("MainWindow", "书名"))
        self.p_chaxun.setText(_translate("MainWindow", "查询"))
        self.p_quxiaoCX.setText(_translate("MainWindow", "取消查询"))
        self.p_tuichu.setText(_translate("MainWindow", "退出"))
        self.groupBox_2.setTitle(_translate("MainWindow", "图书信息"))
        self.label.setText(_translate("MainWindow", "图书封面"))
        self.dbLabPhoto.setText(_translate("MainWindow", "dbLabPhoto"))
        self.label_2.setText(_translate("MainWindow", "ISBN"))
        self.label_3.setText(_translate("MainWindow", "书名"))
        self.label_4.setText(_translate("MainWindow", "作者"))
        self.label_5.setText(_translate("MainWindow", "出版社"))
        self.label_6.setText(_translate("MainWindow", "出版日期"))
        self.label_7.setText(_translate("MainWindow", "评分"))

